name = "proxy-worker"
main = "index.js"
compatibility_date = "2025-12-12"

# Раскомментируйте для настройки custom domain
# routes = [
#   { pattern = "example.com/*", zone_name = "example.com" }
# ]
